import { BUCKET_NAME } from "./aws.ts";

export interface ElevenLabsVoice {
  id: string;
  name: string;
  gender: "female" | "male" | "neutral";
  description: string;
  idioma: string;
  language: string;
  codigoIdioma: string;
  idiomasSoportados: string[];
  multilingue: boolean;
  mp3: string;
  preview_url?: string | null;
}

const IDIOMAS_MULTILINGUAL_V2 = [
  "es", "en", "pt", "fr", "de", "it", "ja", "ko", "zh", "hi", "ar", "ru", "pl", "nl", "tr", "sv", "id", "fil", "uk", "el", "cs", "fi", "ro", "da", "bg", "ms", "sk", "hr", "ta"
];

const getS3Mp3Url = (name: string) =>
  `https://${BUCKET_NAME}.s3.us-east-1.amazonaws.com/VOCES_AUDIO_ELEVENSLAB/${name}.mp3`;

export const SPANISH_VOICES: ElevenLabsVoice[] = [
  // 👩 VOCES FEMENINAS
  {
    id: "XrExE9yKIg1WjnnlVkGX",
    name: "Matilda",
    gender: "female",
    description: "Conocedora, profesional",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Matilda"),
    preview_url: getS3Mp3Url("Matilda"),
  },
  {
    id: "EXAVITQu4vr4xnSDxMaL",
    name: "Sarah",
    gender: "female",
    description: "Madura, tranquilizadora, segura",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Sarah"),
    preview_url: getS3Mp3Url("Sarah"),
  },
  {
    id: "FGY2WhTYpPnrIDTdsKH5",
    name: "Laura",
    gender: "female",
    description: "Entusiasta, peculiar",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Laura"),
    preview_url: getS3Mp3Url("Laura"),
  },
  {
    id: "Xb7hH8MSUJpSbSDYk0k2",
    name: "Alice",
    gender: "female",
    description: "Educadora clara y atractiva",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Alice"),
    preview_url: getS3Mp3Url("Alice"),
  },
  {
    id: "hpp4J3VqNfWAUOO0d1Us",
    name: "Bella",
    gender: "female",
    description: "Profesional, brillante, cálida",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Bella"),
    preview_url: getS3Mp3Url("Bella"),
  },
  {
    id: "cgSgspJ2msm6clMCkdW9",
    name: "Jessica",
    gender: "female",
    description: "Juguetona, brillante",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Jessica"),
    preview_url: getS3Mp3Url("Jessica"),
  },
  {
    id: "pFZP5JQG7iQjIQuC4Bku",
    name: "Lily",
    gender: "female",
    description: "Actriz con voz aterciopelada",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Lily"),
    preview_url: getS3Mp3Url("Lily"),
  },

  // 👨 VOCES MASCULINAS / NEUTRALES
  {
    id: "pNInz6obpgDQGcFmaJgB",
    name: "Adam",
    gender: "male",
    description: "Dominante, firme",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Adam"),
    preview_url: getS3Mp3Url("Adam"),
  },
  {
    id: "CwhRBWXzGAHq8TQ4Fs17",
    name: "Roger",
    gender: "male",
    description: "Relajado, casual, resonante",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Roger"),
    preview_url: getS3Mp3Url("Roger"),
  },
  {
    id: "IKne3meq5aSn9XLyUdCD",
    name: "Charlie",
    gender: "male",
    description: "Profundo, seguro, enérgico",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Charlie"),
    preview_url: getS3Mp3Url("Charlie"),
  },
  {
    id: "JBFqnCBsd6RMkjVDRZzb",
    name: "George",
    gender: "male",
    description: "Narrador cálido y cautivador",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("George"),
    preview_url: getS3Mp3Url("George"),
  },
  {
    id: "N2lVS1w4EtoT3dr4eOWO",
    name: "Callum",
    gender: "male",
    description: "Embaucador ronco",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Callum"),
    preview_url: getS3Mp3Url("Callum"),
  },
  {
    id: "SAz9YHcvj6GT2YYXdXww",
    name: "River",
    gender: "neutral",
    description: "Relajado, neutral, informativo",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("River"),
    preview_url: getS3Mp3Url("River"),
  },
  {
    id: "SOYHLrjzK2X1ezoPC6cr",
    name: "Harry",
    gender: "male",
    description: "Guerrero feroz",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Harry"),
    preview_url: getS3Mp3Url("Harry"),
  },
  {
    id: "TX3LPaxmHKxFdv7VOQHJ",
    name: "Liam",
    gender: "male",
    description: "Creador de redes sociales enérgico",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Liam"),
    preview_url: getS3Mp3Url("Liam"),
  },
  {
    id: "bIHbv24MWmeRgasZH58o",
    name: "Will",
    gender: "male",
    description: "Optimista relajado",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Will"),
    preview_url: getS3Mp3Url("Will"),
  },
  {
    id: "cjVigY5qzO86Huf0OWal",
    name: "Eric",
    gender: "male",
    description: "Suave, confiable",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Eric"),
    preview_url: getS3Mp3Url("Eric"),
  },
  {
    id: "iP95p4xoKVk53GoZ742B",
    name: "Chris",
    gender: "male",
    description: "Encantador, con los pies en la tierra",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Chris"),
    preview_url: getS3Mp3Url("Chris"),
  },
  {
    id: "nPczCjzI2devNBz1zQrb",
    name: "Brian",
    gender: "male",
    description: "Profundo, resonante y reconfortante",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Brian"),
    preview_url: getS3Mp3Url("Brian"),
  },
  {
    id: "onwK4e9ZLuTAKqWW03F9",
    name: "Daniel",
    gender: "male",
    description: "Locutor constante",
    idioma: "Español (Multilingüe)",
    language: "Spanish (Multilingual)",
    codigoIdioma: "es",
    idiomasSoportados: IDIOMAS_MULTILINGUAL_V2,
    multilingue: true,
    mp3: getS3Mp3Url("Daniel"),
    preview_url: getS3Mp3Url("Daniel"),
  },
];

export const config = {
  elevenLabs: {
    defaultVoiceId: "EXAVITQu4vr4xnSDxMaL", // Sarah
    modelId: "eleven_multilingual_v2",
    sampleFolder: "VOCES_AUDIO_ELEVENSLAB",
    sampleText: "HOLA ESTO ES UNA PRUEBA DE MI VOZ EN HOMERO",
  },
  server: {
    port: Number(Deno.env.get("PORT")) || 8000,
  },
};
